# Streamlit Cloud Secrets Template
# Copy this file to .streamlit/secrets.toml and fill in your actual values

# Google OAuth Credentials
GOOGLE_CLIENT_ID = "your_google_client_id_here"
GOOGLE_CLIENT_SECRET = "your_google_client_secret_here"

# Firebase Configuration (if needed)
# Add your Firebase service account key content here
# Or use the JSON file approach as in the current setup 