[google_oauth]
client_id = "YOUR_CLIENT_ID_HERE"
client_secret = "YOUR_CLIENT_SECRET_HERE"
[firebase]
type = "service_account"
project_id = "gdg-attenx"
private_key_id = "78363512637bbf26929b0d138d052da114f57990"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMCBowjLgoYApG
iSEO/4DfVDJsizEdhuYrOZHPME8LbQ9/cgawc+EzGNclwsKjCkoXOh65OxPGiOIw
dG/+oTa89/C3ThQQt1iQjAUZ+YcCC4jYPQk9LAS1l4vxdC17HV7Px3NtxcwRX1Sx
9w4kdnIyNXAyNxmqJ4XOGSJKZaFzLIxZkNFC5mx+bPm4rFhsZQjcw3uwm22967bo
+JBGtGDEifld/KPhRGiIoUKIvu494VxAuo2muVPmu5XqhEQuD/1fAqB2lLMHC0Ex
13rmwzpgLFbW/ChFMH//3Y9GL6L14E2nso3C8pIlraw1vY6ZE0mY9E84nP7NgMa8
VWXJkvDTAgMBAAECggEAJhchJI0w2EDNyktRg6ZJnefvHfqCadvEXq95vC9tolly
+j0EaK7JjSuHBwKsKZoDKQDtuXEBCSCG8brbKbNZL8AuDVqjPlesThgF38qI3OXg
X1ZNwkDUhD5Nnv8sen6KM8otj4HMzjV471yLJF2EhkEZuBY3UV/diBODJlaA5KpH
qWiiUayGhqd1ZhoXRLB+kd39Peli7StfvRkMlZlx66D4QpY97UhnPeYbOFBe7UFP
fsYig1xFm3BH05BWKRWmdw7KwltGESlqtsF3ugbRhhns50rdfmdl+t2Jf1nqA9ig
uKB73wDLHRe+XGT5nT9lE841PGSaJVTBUrw8r7oU2QKBgQD8t3eGy5jy0NhBi4H2
7XCaKAn9SEbCqW1X8KfsXvb1yOmu5AdoR2MHMl9rCEsFZkV9izDSOcJ4EETqJf8u
PBDy4DxrEjK6mmaSbSIuw19F5J5dp8BwUEUV3kiomZQVnN0huf+qeWlvmnFA4H47
jiW1mwDc7GV52NSg/kPnhYdPXQKBgQDOrrWjN6gHQ5/OzdPVSqacuvK3rW2c0chx
P1AqaMvCtsTYxBnBL+qeEl+ygAWdxrf0YlqFxGiO4wp9kld6Y/3rqPNoRnC7zLbY
0jiVMWs0N7CkxjOlhHUlfw6wjBrNO38nIbXj8lVOBoVOukJmZHBdVd2qBot0F74Q
tDj3mjat7wKBgA1C11vUbTc4rFBsMKqzdPgx56xJ0aS/XUSDFVy68vycyV5rCtR3
AoRLKWSlb8JdxoG6/xnY/BJu0B71VXmonz8PczwvHUhbd8xxO5z2lZZGU+UYO2np
XGa0Xl2yiWnE7Hmrl/XrHxRDJ3Q/E4Cuid4IvzfYk86cCTRVg1yvzhTlAoGASmRe
Iop043B2w/QX7Cy7faxYkr5MtuZXdFOqoikoNkSc47zp3DxIAW9xnIkx/FE7gy4n
kQBZ9hxIeVxEOlxlV/5u5jh8eUw9ABvim+i2wovM+/IPQuNDWyS5f9heCUMCCG68
zng6NiRotSaboclDHIU8jOdgKIAnPFHyM0UBq2cCgYEAn9C0JrLsamb83884oEZf
mBh8lJAt7qejPU57Hi81mReYuDYMt8xVSmBHF0/GJCHlJf9ydxBgE6njmWCZKX3z
PiazkkoB7xh+j0PZQW06TA8Jph+n68TPbFvM/OHE02Odjna5Mfx4mnHhmTwdhvY9
rkkoXCD1CXwFszP/LJ0nAeM=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@gdg-attenx.iam.gserviceaccount.com"
client_id = "110827570727658938198"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40gdg-attenx.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
